// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/product.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductService_ValidateBundle_FullMethodName = "/product.ProductService/ValidateBundle"
	ProductService_DeductBundle_FullMethodName   = "/product.ProductService/DeductBundle"
	ProductService_ValidateStock_FullMethodName  = "/product.ProductService/ValidateStock"
	ProductService_ReduceStock_FullMethodName    = "/product.ProductService/ReduceStock"
)

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductServiceClient interface {
	ValidateBundle(ctx context.Context, in *BundleRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
	DeductBundle(ctx context.Context, in *BundleRequest, opts ...grpc.CallOption) (*DeductResponse, error)
	ValidateStock(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (*StockValidateResponse, error)
	ReduceStock(ctx context.Context, in *StockReductionRequest, opts ...grpc.CallOption) (*StockReductionResponse, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) ValidateBundle(ctx context.Context, in *BundleRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, ProductService_ValidateBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) DeductBundle(ctx context.Context, in *BundleRequest, opts ...grpc.CallOption) (*DeductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeductResponse)
	err := c.cc.Invoke(ctx, ProductService_DeductBundle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ValidateStock(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (*StockValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockValidateResponse)
	err := c.cc.Invoke(ctx, ProductService_ValidateStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ReduceStock(ctx context.Context, in *StockReductionRequest, opts ...grpc.CallOption) (*StockReductionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockReductionResponse)
	err := c.cc.Invoke(ctx, ProductService_ReduceStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
// All implementations must embed UnimplementedProductServiceServer
// for forward compatibility.
type ProductServiceServer interface {
	ValidateBundle(context.Context, *BundleRequest) (*ValidateResponse, error)
	DeductBundle(context.Context, *BundleRequest) (*DeductResponse, error)
	ValidateStock(context.Context, *StockRequest) (*StockValidateResponse, error)
	ReduceStock(context.Context, *StockReductionRequest) (*StockReductionResponse, error)
	mustEmbedUnimplementedProductServiceServer()
}

// UnimplementedProductServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductServiceServer struct{}

func (UnimplementedProductServiceServer) ValidateBundle(context.Context, *BundleRequest) (*ValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateBundle not implemented")
}
func (UnimplementedProductServiceServer) DeductBundle(context.Context, *BundleRequest) (*DeductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeductBundle not implemented")
}
func (UnimplementedProductServiceServer) ValidateStock(context.Context, *StockRequest) (*StockValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateStock not implemented")
}
func (UnimplementedProductServiceServer) ReduceStock(context.Context, *StockReductionRequest) (*StockReductionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReduceStock not implemented")
}
func (UnimplementedProductServiceServer) mustEmbedUnimplementedProductServiceServer() {}
func (UnimplementedProductServiceServer) testEmbeddedByValue()                        {}

// UnsafeProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServiceServer will
// result in compilation errors.
type UnsafeProductServiceServer interface {
	mustEmbedUnimplementedProductServiceServer()
}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	// If the following call panics, it indicates UnimplementedProductServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductService_ServiceDesc, srv)
}

func _ProductService_ValidateBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ValidateBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_ValidateBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ValidateBundle(ctx, req.(*BundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_DeductBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BundleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).DeductBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_DeductBundle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).DeductBundle(ctx, req.(*BundleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ValidateStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ValidateStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_ValidateStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ValidateStock(ctx, req.(*StockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ReduceStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockReductionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ReduceStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductService_ReduceStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ReduceStock(ctx, req.(*StockReductionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductService_ServiceDesc is the grpc.ServiceDesc for ProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateBundle",
			Handler:    _ProductService_ValidateBundle_Handler,
		},
		{
			MethodName: "DeductBundle",
			Handler:    _ProductService_DeductBundle_Handler,
		},
		{
			MethodName: "ValidateStock",
			Handler:    _ProductService_ValidateStock_Handler,
		},
		{
			MethodName: "ReduceStock",
			Handler:    _ProductService_ReduceStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/product.proto",
}
